### ISSUE TITLE
Result in keystone-operator passing operator-sdk scorecard

### ISSUE THREAD

**Issue by leifmadsen** [openstack-k8s-operators/keystone-operator#1]
Here are the current results of `keystone-operator` and it's scorecard test results. This is mostly here for myself unless someone gets to it first.

**Environment**

* Fedora 31
* crc version: 1.6.0+8ef676f
  OpenShift version: 4.3.0 (embedded in binary)

**Results**

```
operator-sdk scorecard
INFO[0000] Using config file: /home/sysop/src/github.com/openstack-k8s-operators/keystone-operator/.osdk-scorecard.yaml 
basic:
	Writing into CRs has an effect      : pass
	Labels: 
		"necessity":"required"
		"suite":"basic"
		"test":"writingintocrshaseffecttest"

	Spec Block Exists                   : pass
	Labels: 
		"necessity":"required"
		"suite":"basic"
		"test":"checkspectest"

	Status Block Exists                 : fail
	Labels: 
		"suite":"basic"
		"test":"checkstatustest"
		"necessity":"required"
	Suggestions: 
		Add a 'status' field to your Custom Resource

olm:
	Bundle Validation Test              : fail
	Labels: 
		"necessity":"required"
		"suite":"olm"
		"test":"bundlevalidationtest"
	Errors: 
		Error: Value error getting bundles from manifests dir "deploy/olm-catalog/service-telemetry-operator/1.0.1/metadata": invalid file: <nil>: parse manifests from "deploy/olm-catalog/service-telemetry-operator/1.0.1/metadata"
	Log:
		time="2020-03-19T16:07:49-04:00" level=info msg="loading Bundles" dir=deploy/olm-catalog/service-telemetry-operator/1.0.1/metadata
time="2020-03-19T16:07:49-04:00" level=info msg="loading Packages and Entries" dir=deploy/olm-catalog/service-telemetry-operator/1.0.1/metadata


	Provided APIs have validation       : pass
	Labels: 
		"necessity":"required"
		"suite":"olm"
		"test":"crdshavevalidationtest"

	Owned CRDs have resources listed    : fail
	Labels: 
		"necessity":"required"
		"suite":"olm"
		"test":"crdshaveresourcestest"
	Suggestions: 
		If it would be helpful to an end-user to understand or troubleshoot your CR, consider adding resources [jobs/v1 pods/v1 configmaps/v1 secrets/v1] to the resources section for owned CRD KeystoneApi

	Spec fields with descriptors        : fail
	Labels: 
		"necessity":"required"
		"suite":"olm"
		"test":"specdescriptorstest"
	Suggestions: 
		Add a spec descriptor for databaseHostname
		Add a spec descriptor for replicas
		Add a spec descriptor for containerImage
		Add a spec descriptor for databaseAdminPassword
		Add a spec descriptor for databaseAdminUsername
		Add a spec descriptor for databasePassword
		Add a spec descriptor for mysqlContainerImage
		Add a spec descriptor for adminPassword
		Add a spec descriptor for apiEndpoint

	Status fields with descriptors      : pass
	Labels: 
		"suite":"olm"
		"test":"statusdescriptorstest"
		"necessity":"required"
```

And the scorecard configuration I created:

```
cat .osdk-scorecard.yaml 
scorecard:
  version: v1alpha2
  output: text
  bundle: deploy/olm-catalog/service-telemetry-operator/1.0.1/metadata
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/keystone.openstack.org_keystoneapis_cr.yaml"
        csv-path: "deploy/olm-catalog/keystone-operator/0.0.1/keystone-operator.v0.0.1.clusterserviceversion.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/keystone.openstack.org_keystoneapis_cr.yaml"
        csv-path: "deploy/olm-catalog/keystone-operator/0.0.1/keystone-operator.v0.0.1.clusterserviceversion.yaml"
```
